from robotix.structure.kind.mind.consciousness.awareness.self.awareness import Level0
from robotix.structure.kind.mind.consciousness.awareness.self.awareness import Level0
from robotix.structure.kind.mind.consciousness.awareness.self.awareness import Level2
from robotix.structure.kind.mind.consciousness.awareness.self.awareness import Level3
from robotix.structure.kind.mind.consciousness.awareness.self.awareness import Level4
from robotix.structure.kind.mind.consciousness.awareness.self.awareness import Level_5
from typing import List

class Levels:
    """
    - TODO: All levels of awareness need to be reviewed as they are all generated by GPT
    """
    def __init__(self):
        self._memebers = List[Level0, Level1, Level2, Level3, Level4, Level_5]

    def get_memebers(self)->List[Level]:
        return self._memebers
