from typing import Optional, Any

from robotix.structure.kind.body.nervous.neuron.population_activity_field.population_activity_field import \
    PopulationActivityField
from robotix.structure.kind.mind.process.kind.memory.composite.trace.interface import Interface as TraceInterface
from robotix.structure.kind.mind.process.kind.memory.composite.trace.kind.core.kind import Kind


class Trace(TraceInterface):
    """
    - trace is the connection between nervous system and mind. on one hand it receives potential activity fieelds and on theother hand it converts it to a nested group point such as a dictionary or a composite pattern
    - This is a lost in time memory cell
    An role or a sensor read happens
    - the smalleast group part of the momery being generated by spikes population field
    - this is the boundry between body brain and mind mind
    - spikes can not be decorated or be composite or decorated
    - trace covers from spike activit field to structed group
    - this is the leaf of composite pattern
    """

    def __init__(self, population_activity_field: Optional[PopulationActivityField], name:Optional[str]):
        """

        Args:
            population_activity_field:
            name:
        """
        self._population_activity_field = population_activity_field
        # it is just a point, a group point, without a population it has no meaning
        self._formatted_data: Any = None

        # is it a command? a lidar sensor? a initial_mission? This must be guessed from formatted group
        self._kind: Optional[Any] = None
        # is what is given from population
        self._name = name



    @classmethod
    def init_from_formatted_data_and_kind_and_name(cls, formatted_data: Any, kind:Kind, name:Optional[str])-> "Trace":
        this_object = cls(None, name)
        this_object._formatted_data = formatted_data
        this_object._kind = kind
        return this_object

    def get_formatted_data(self) -> Any:
        return self._formatted_data

    def get_nervous_population_activity_field(self) -> Optional[PopulationActivityField]:
        return self._population_activity_field

    def get_kind(self) -> Kind:
        if self._kind is None:
            self._kind = self.extract_kind()
        return self._kind



    def set_name(self, name: Optional[str]):
        """
        This can be set from a population such as a trace group
        Args:
            name:

        Returns:

        """
        self._name = name

    def extract_kind(self)->Kind:
        """"""
        pass

